name: flake8 lint
on:
  push:
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-20.04
    name: flake8 lint
    steps:
      - name: Setup python for flake8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: actions/checkout@v3
      - name: Install tox
        run: python -m pip install tox
      - name: Setup flake8
        run: tox --notest -e flake8
      - name: Run flake8
        run: tox -e flake8
